// Generado por etl/web_config.sh desde api.categories — no editar a mano.
window.GEODB_CATEGORIES = [{"code":"salut","parent":null,"label":"Salut","color":"#ef4444","sort":10,"analysis":false,"is_service":true,"n":1657}, 
 {"code":"hospital","parent":"salut","label":"Hospital","color":"#ef4444","sort":11,"analysis":true,"is_service":true,"n":44}, 
 {"code":"atencio_primaria","parent":"salut","label":"Atenció primària (CAP)","color":"#ef4444","sort":12,"analysis":true,"is_service":true,"n":53}, 
 {"code":"farmacia","parent":"salut","label":"Farmàcia","color":"#ef4444","sort":13,"analysis":true,"is_service":true,"n":1024}, 
 {"code":"dentista","parent":"salut","label":"Dentista","color":"#ef4444","sort":14,"analysis":true,"is_service":true,"n":152}, 
 {"code":"consulta_centre_medic","parent":"salut","label":"Consulta i centre mèdic privat","color":"#ef4444","sort":15,"analysis":true,"is_service":true,"n":253}, 
 {"code":"salut_mental","parent":"salut","label":"Salut mental","color":"#ef4444","sort":16,"analysis":true,"is_service":true,"n":12}, 
 {"code":"altres_sanitaris","parent":"salut","label":"Altres serveis sanitaris","color":"#ef4444","sort":17,"analysis":true,"is_service":true,"n":119}, 
 {"code":"social","parent":null,"label":"Serveis socials","color":"#ec4899","sort":20,"analysis":false,"is_service":true,"n":172}, 
 {"code":"residencia","parent":"social","label":"Residència","color":"#ec4899","sort":21,"analysis":true,"is_service":true,"n":92}, 
 {"code":"casal_gent_gran","parent":"social","label":"Casal de gent gran","color":"#ec4899","sort":22,"analysis":true,"is_service":true,"n":2}, 
 {"code":"atencio_social","parent":"social","label":"Atenció social","color":"#ec4899","sort":23,"analysis":true,"is_service":true,"n":78}, 
 {"code":"educacio","parent":null,"label":"Educació","color":"#3b82f6","sort":30,"analysis":false,"is_service":true,"n":982}, 
 {"code":"escola_bressol","parent":"educacio","label":"Escola bressol (0-3)","color":"#3b82f6","sort":31,"analysis":true,"is_service":true,"n":163}, 
 {"code":"escola","parent":"educacio","label":"Escola (infantil i primària)","color":"#3b82f6","sort":32,"analysis":true,"is_service":true,"n":239}, 
 {"code":"institut","parent":"educacio","label":"Institut (secundària)","color":"#3b82f6","sort":33,"analysis":true,"is_service":true,"n":64}, 
 {"code":"institut_escola","parent":"educacio","label":"Institut escola","color":"#3b82f6","sort":34,"analysis":true,"is_service":true,"n":19}, 
 {"code":"centre_integrat","parent":"educacio","label":"Centre integrat (diversos nivells)","color":"#3b82f6","sort":35,"analysis":true,"is_service":true,"n":32}, 
 {"code":"universitat","parent":"educacio","label":"Universitat","color":"#3b82f6","sort":36,"analysis":true,"is_service":true,"n":130}, 
 {"code":"educacio_especial","parent":"educacio","label":"Educació especial","color":"#3b82f6","sort":37,"analysis":true,"is_service":true,"n":4}, 
 {"code":"formacio_adults","parent":"educacio","label":"Formació d'adults","color":"#3b82f6","sort":38,"analysis":true,"is_service":true,"n":2}, 
 {"code":"escola_idiomes","parent":"educacio","label":"Escola d'idiomes","color":"#3b82f6","sort":39,"analysis":true,"is_service":true,"n":3}, 
 {"code":"formacio_no_reglada","parent":"educacio","label":"Formació no reglada","color":"#3b82f6","sort":40,"analysis":true,"is_service":true,"n":326}, 
 {"code":"cultura","parent":null,"label":"Cultura i comunitat","color":"#8b5cf6","sort":50,"analysis":false,"is_service":true,"n":1012}, 
 {"code":"biblioteca","parent":"cultura","label":"Biblioteca","color":"#8b5cf6","sort":51,"analysis":true,"is_service":true,"n":82}, 
 {"code":"centre_civic","parent":"cultura","label":"Centre cívic","color":"#8b5cf6","sort":52,"analysis":true,"is_service":true,"n":350}, 
 {"code":"equipament_cultural","parent":"cultura","label":"Equipament cultural (museu, teatre, cinema)","color":"#8b5cf6","sort":53,"analysis":true,"is_service":true,"n":347}, 
 {"code":"bibliobus","parent":"cultura","label":"Bibliobús (parada)","color":"#8b5cf6","sort":54,"analysis":true,"is_service":true,"n":0}, 
 {"code":"lloc_de_culte","parent":"cultura","label":"Lloc de culte","color":"#8b5cf6","sort":55,"analysis":true,"is_service":true,"n":233}, 
 {"code":"administracio","parent":null,"label":"Administració","color":"#14b8a6","sort":60,"analysis":false,"is_service":true,"n":315}, 
 {"code":"ajuntament","parent":"administracio","label":"Ajuntament","color":"#14b8a6","sort":61,"analysis":true,"is_service":true,"n":7}, 
 {"code":"seguretat_emergencies","parent":"administracio","label":"Seguretat i emergències","color":"#14b8a6","sort":62,"analysis":true,"is_service":true,"n":49}, 
 {"code":"correus","parent":"administracio","label":"Correus","color":"#14b8a6","sort":63,"analysis":true,"is_service":true,"n":54}, 
 {"code":"altres_administracio","parent":"administracio","label":"Altres serveis administratius","color":"#14b8a6","sort":64,"analysis":true,"is_service":true,"n":205}, 
 {"code":"esports","parent":null,"label":"Esports","color":"#f97316","sort":70,"analysis":false,"is_service":true,"n":1740}, 
 {"code":"pavello_centre_esportiu","parent":"esports","label":"Pavelló o centre esportiu","color":"#f97316","sort":71,"analysis":true,"is_service":true,"n":204}, 
 {"code":"camp_pista","parent":"esports","label":"Camp o pista","color":"#f97316","sort":72,"analysis":true,"is_service":true,"n":1206}, 
 {"code":"piscina","parent":"esports","label":"Piscina d'ús públic","color":"#f97316","sort":73,"analysis":true,"is_service":true,"n":26}, 
 {"code":"gimnas","parent":"esports","label":"Gimnàs","color":"#f97316","sort":74,"analysis":true,"is_service":true,"n":188}, 
 {"code":"altres_esports","parent":"esports","label":"Altres instal·lacions esportives","color":"#f97316","sort":75,"analysis":true,"is_service":true,"n":116}, 
 {"code":"lleure","parent":null,"label":"Espais verds i lleure","color":"#65a30d","sort":80,"analysis":false,"is_service":true,"n":3982}, 
 {"code":"parc_jardi","parent":"lleure","label":"Parc o jardí","color":"#65a30d","sort":81,"analysis":true,"is_service":true,"n":2993}, 
 {"code":"area_joc_infantil","parent":"lleure","label":"Àrea de joc infantil","color":"#65a30d","sort":82,"analysis":true,"is_service":true,"n":824}, 
 {"code":"area_picnic","parent":"lleure","label":"Àrea de pícnic","color":"#65a30d","sort":83,"analysis":true,"is_service":true,"n":64}, 
 {"code":"area_gossos","parent":"lleure","label":"Àrea per a gossos","color":"#65a30d","sort":84,"analysis":true,"is_service":true,"n":100}, 
 {"code":"espai_natural","parent":"lleure","label":"Espai natural","color":"#65a30d","sort":85,"analysis":true,"is_service":true,"n":1}, 
 {"code":"comerc","parent":null,"label":"Comerç","color":"#eab308","sort":90,"analysis":false,"is_service":true,"n":7475}, 
 {"code":"alimentacio","parent":"comerc","label":"Alimentació (comerç quotidià)","color":"#eab308","sort":91,"analysis":true,"is_service":true,"n":3006}, 
 {"code":"comerc_no_quotidia","parent":"comerc","label":"Comerç no quotidià","color":"#eab308","sort":92,"analysis":true,"is_service":true,"n":4201}, 
 {"code":"salut_cura_personal","parent":"comerc","label":"Òptica, herbolari i cura personal","color":"#eab308","sort":93,"analysis":true,"is_service":true,"n":268}, 
 {"code":"restauracio","parent":null,"label":"Restauració","color":"#d946ef","sort":100,"analysis":false,"is_service":true,"n":7574}, 
 {"code":"restaurant","parent":"restauracio","label":"Restaurant","color":"#d946ef","sort":101,"analysis":true,"is_service":true,"n":4471}, 
 {"code":"bar_cafeteria","parent":"restauracio","label":"Bar i cafeteria","color":"#d946ef","sort":102,"analysis":true,"is_service":true,"n":3028}, 
 {"code":"oci_nocturn","parent":"restauracio","label":"Oci nocturn","color":"#d946ef","sort":103,"analysis":true,"is_service":true,"n":75}, 
 {"code":"serveis","parent":null,"label":"Serveis","color":"#94a3b8","sort":110,"analysis":false,"is_service":true,"n":4555}, 
 {"code":"banca_assegurances","parent":"serveis","label":"Banca i assegurances","color":"#94a3b8","sort":111,"analysis":true,"is_service":true,"n":735}, 
 {"code":"serveis_personals","parent":"serveis","label":"Serveis personals (perruqueria, bugaderia)","color":"#94a3b8","sort":112,"analysis":true,"is_service":true,"n":1219}, 
 {"code":"automocio","parent":"serveis","label":"Automoció (taller, benzinera)","color":"#94a3b8","sort":113,"analysis":true,"is_service":true,"n":429}, 
 {"code":"oficines","parent":"serveis","label":"Oficines","color":"#94a3b8","sort":114,"analysis":true,"is_service":true,"n":2099}, 
 {"code":"veterinari","parent":"serveis","label":"Veterinari","color":"#94a3b8","sort":115,"analysis":true,"is_service":true,"n":62}, 
 {"code":"funeraria","parent":"serveis","label":"Funerària","color":"#94a3b8","sort":116,"analysis":true,"is_service":true,"n":11}, 
 {"code":"turisme","parent":null,"label":"Turisme","color":"#b45309","sort":120,"analysis":false,"is_service":true,"n":1845}, 
 {"code":"allotjament","parent":"turisme","label":"Allotjament","color":"#b45309","sort":121,"analysis":true,"is_service":true,"n":780}, 
 {"code":"atractiu_turistic","parent":"turisme","label":"Atractiu turístic (mirador, monument)","color":"#b45309","sort":122,"analysis":true,"is_service":true,"n":1038}, 
 {"code":"oficina_turisme","parent":"turisme","label":"Oficina de turisme","color":"#b45309","sort":123,"analysis":true,"is_service":true,"n":27}, 
 {"code":"mobilitat","parent":null,"label":"Mobilitat","color":"#06b6d4","sort":130,"analysis":false,"is_service":true,"n":7726}, 
 {"code":"parada","parent":"mobilitat","label":"Parada de transport públic","color":"#06b6d4","sort":131,"analysis":true,"is_service":true,"n":2796}, 
 {"code":"estacio","parent":"mobilitat","label":"Estació","color":"#06b6d4","sort":132,"analysis":true,"is_service":true,"n":170}, 
 {"code":"aparcament_public","parent":"mobilitat","label":"Aparcament públic","color":"#06b6d4","sort":133,"analysis":true,"is_service":true,"n":736}, 
 {"code":"aparcament_bicicletes","parent":"mobilitat","label":"Aparcament de bicicletes","color":"#06b6d4","sort":134,"analysis":true,"is_service":true,"n":3006}, 
 {"code":"recarrega_electrica","parent":"mobilitat","label":"Recàrrega de vehicle elèctric","color":"#06b6d4","sort":135,"analysis":true,"is_service":true,"n":150}, 
 {"code":"taxi","parent":"mobilitat","label":"Parada de taxi","color":"#06b6d4","sort":136,"analysis":true,"is_service":true,"n":279}, 
 {"code":"bicicleta_compartida","parent":"mobilitat","label":"Bicicleta compartida (Bicing)","color":"#06b6d4","sort":137,"analysis":true,"is_service":true,"n":589}, 
 {"code":"infraestructura","parent":null,"label":"Infraestructura (no és servei)","color":"#525252","sort":900,"analysis":false,"is_service":false,"n":19036}, 
 {"code":"senyalitzacio","parent":"infraestructura","label":"Senyalització","color":"#525252","sort":901,"analysis":false,"is_service":false,"n":1064}, 
 {"code":"punt_aturada_vehicle","parent":"infraestructura","label":"Punt d'aturada del vehicle","color":"#525252","sort":902,"analysis":false,"is_service":false,"n":2947}, 
 {"code":"mobiliari_urba","parent":"infraestructura","label":"Mobiliari urbà","color":"#525252","sort":903,"analysis":false,"is_service":false,"n":15025}, 
 {"code":"privat","parent":null,"label":"Ús privat (no és servei)","color":"#404040","sort":910,"analysis":false,"is_service":false,"n":3450}, 
 {"code":"piscina_privada","parent":"privat","label":"Piscina privada","color":"#404040","sort":911,"analysis":false,"is_service":false,"n":1459}, 
 {"code":"aparcament_privat_clients","parent":"privat","label":"Aparcament privat o de clients","color":"#404040","sort":912,"analysis":false,"is_service":false,"n":1795}, 
 {"code":"installacio_privada","parent":"privat","label":"Instal·lació privada","color":"#404040","sort":913,"analysis":false,"is_service":false,"n":196}, 
 {"code":"altres","parent":null,"label":"Altres","color":"#737373","sort":990,"analysis":false,"is_service":false,"n":286}, 
 {"code":"local_buit","parent":"altres","label":"Local buit","color":"#737373","sort":991,"analysis":false,"is_service":false,"n":100}, 
 {"code":"sense_classificar","parent":"altres","label":"Sense classificar","color":"#737373","sort":992,"analysis":false,"is_service":false,"n":186}]
;
